import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "sonner";
import { ClientProvider } from "@/components/clerkprovider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { DietProvider } from "@/context/diet-list";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diet App",
  description: "Generated by Harun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey="jotion-theme-2"
          >
            {children}
            <Toaster position="bottom-center" expand={false} richColors />
          </ThemeProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
